### ISSUE TITLE
Dropping https on login.

### ISSUE THREAD

**Issue by trevore** [oculusinfo/OpenAds#5]
If you go to this URL

https://openads.istresearch.com:8443/openads/

And then login, it drops you to...

openads.istresearch.com:8443/openads/

Which does not work because that port is speaking https. We need the protocol to persist. Right now the work around is to repeatedly re-add the https.

**Comment by dschroh** [comment]
Added an HTTPS endpoint to the tomcat config. If you connect to the Tomcat from the load balancer via https, there should be any problem. Latest Docker container was updated last week.
